version: '3.8'

services:
  # Nginx server for HTTP challenge
  nginx-certbot:
    image: nginx:alpine
    container_name: certbot-nginx
    ports:
      - "80:80"
    volumes:
      - ./certbot/www:/var/www/certbot:ro
      - ./nginx-certbot.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - certbot-network

  # Certbot for certificate generation with user mapping
  certbot:
    image: certbot/certbot
    container_name: certbot-generator
    # Run certbot as current user to avoid root ownership issues
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - ./certbot/conf:/etc/letsencrypt:rw
      - ./certbot/www:/var/www/certbot:rw
      - ./ssl:/etc/letsencrypt/live/prismscope.ai:rw
    networks:
      - certbot-network
    environment:
      # Ensure certbot uses the correct paths
      - CERTBOT_NONINTERACTIVE=1

networks:
  certbot-network:
    driver: bridge