# Let's Encrypt ClusterIssuer for automatic SSL certificate management
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    # The ACME server URL for Let's Encrypt production
    server: https://acme-v02.api.letsencrypt.org/directory
    
    # Email address used for ACME registration
    email: harrison@provoco.ai
    
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-prod-private-key
    
    # Enable the HTTP-01 challenge provider
    solvers:
    - http01:
        ingress:
          class: nginx
          podTemplate:
            spec:
              # Security context for cert-manager pods
              securityContext:
                runAsNonRoot: true
                runAsUser: 1001
                runAsGroup: 1001
                seccompProfile:
                  type: RuntimeDefault
              containers:
              - name: acme-challenge-solver
                securityContext:
                  allowPrivilegeEscalation: false
                  runAsNonRoot: true
                  runAsUser: 1001
                  runAsGroup: 1001
                  readOnlyRootFilesystem: true
                  capabilities:
                    drop:
                    - ALL

---
# Staging issuer for testing (optional)
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    # The ACME server URL for Let's Encrypt staging (for testing)
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    
    # Email address used for ACME registration
    email: harrison@provoco.ai
    
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-staging-private-key
    
    # Enable the HTTP-01 challenge provider
    solvers:
    - http01:
        ingress:
          class: nginx