apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: cert-manager
spec:
  acme:
    # Let's Encrypt ACME server URL for production
    server: https://acme-v02.api.letsencrypt.org/directory
    
    # Email for Let's Encrypt notifications
    email: harrison@provoco.ai  # Replace with your email
    
    # Private key secret for ACME account
    privateKeySecretRef:
      name: letsencrypt-prod-private-key
    
    # HTTP01 challenge solver
    solvers:
    - http01:
        ingress:
          class: nginx
          podTemplate:
            spec:
              nodeSelector:
                kubernetes.io/os: linux
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  namespace: cert-manager
spec:
  acme:
    # Let's Encrypt ACME server URL for staging (testing)
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    
    # Email for Let's Encrypt notifications
    email: harrison@provoco.ai  # Replace with your email
    
    # Private key secret for ACME account
    privateKeySecretRef:
      name: letsencrypt-staging-private-key
    
    # HTTP01 challenge solver
    solvers:
    - http01:
        ingress:
          class: nginx
          podTemplate:
            spec:
              nodeSelector:
                kubernetes.io/os: linux