# Pod Disruption Budget for high availability
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: prismscope-website-pdb
  namespace: prismscope
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: prismscope-website
      tier: frontend